name: GitHub Actions Demo
on:
  push:
      branches: [main]
      paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: github context variables
      - run:
      
          echo " print github context information ${{toJSON(github)}}"
      - name: runner context variables
      - run:
      
          echo " print github context information ${{toJSON(runner)}}"
          
      - run: |
         echo " the job event ${{github.event_name}}"
         echo " the repo branch ${{github.ref}}"
      - uses: actions/checkout@v3.3.0
      - name: List files in the repository
        run: |
          echo " the list of files ${{github.repository}}"
          
      
    
    
  

 
 
